# Generated by Django 3.2 on 2021-08-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('Brand_name', models.CharField(max_length=100)),
                ('mrp', models.FloatField(default=0)),
                ('Price', models.FloatField(default=0)),
                ('descricption', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=300)),
                ('number_of_items', models.IntegerField()),
                ('images1', models.ImageField(blank=True, default='', upload_to='images')),
                ('images2', models.ImageField(blank=True, default='', upload_to='images')),
                ('images3', models.ImageField(blank=True, default='', upload_to='images')),
                ('images4', models.ImageField(blank=True, default='', upload_to='images')),
                ('images5', models.ImageField(blank=True, default='', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poster', models.ImageField(blank=True, default='', upload_to='media')),
                ('products', models.ManyToManyField(to='store.Product')),
            ],
        ),
    ]
